"""empty message

Revision ID: 0e7c241c65fa
Revises: 541744420d78
Create Date: 2021-11-16 10:31:35.956294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7c241c65fa'
down_revision = '541744420d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 's')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('s', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
